// Modell
const startmodel = {
    app: {
        page: null,
    },

    navbar: {
        confirmDropdown: false,
        saveDropdown: false,
    },

    game: {
        intervalId: null,
    },

    player: {
        money: 0,
        totalManaGathered: 0,
        clicker: {
            cursorStrength: 1,
            intervalId: null,
            intervalActive: false,
            sparklesIsOn: false,
        },
    },

    upgrades: [
        grimoire = {
            id: 1,
            name: "Grimoires",
            amount: 0,
            price: 5,
            strength: 1,
        },
        familiar = {
            id: 2,
            name: "Familiars",
            amount: 0,
            price: 100,
            strength: 4,
        },
        alchemyTable = {
            id: 3,
            name: "Alchemy Tables",
            amount: 0,
            price: 500,
            strength: 16,
        },
        pylon = {
            id: 4,
            name: "Pylons",
            amount: 0,
            price: 1000,
            strength: 64,
        },
        manaFountain = {
            id: 5,
            name: "Mana Fountains",
            amount: 0,
            price: 10000,
            strength: 256,
        },
        manaNexus = {
            id: 6,
            name: "Mana Nexus",
            amount: 0,
            price: 100000,
            strength: 1024,
        },
    ],

    buffs: [
        grimoire = [
            strengthMultiplier1 = {
                id: 1,
                categoryId: 1,
                tier: 1,
                name: "Novice Grimoire",
                price: 50,
                amountCriteria: 5,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier2 = {
                id: 2,
                categoryId: 1,
                tier: 2,
                name: "Apprentice Grimoire",
                price: 250,
                amountCriteria: 10,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier3 = {
                id: 3,
                categoryId: 1,
                tier: 3,
                name: "Adept Grimoire",
                price: 500,
                amountCriteria: 15,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier4 = {
                id: 4,
                categoryId: 1,
                tier: 4,
                name: " Master Grimoire",
                price: 1000,
                amountCriteria: 25,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier5 = {
                id: 5,
                categoryId: 1,
                tier: 5,
                name: "Archmage's Grimoire",
                price: 2500,
                amountCriteria: 50,
                unlocked: false,
                buffMulti: 2,
            },
        ],
        familiar = [
            strengthMultiplier1 = {
                id: 10,
                categoryId: 2,
                tier: 1,
                name: "Tiny Familiar",
                price: 200,
                amountCriteria: 5,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier2 = {
                id: 11,
                categoryId: 2,
                tier: 2,
                name: "Apprentice Familiar",
                price: 1000,
                amountCriteria: 10,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier3 = {
                id: 12,
                categoryId: 2,
                tier: 3,
                name: "Adept Familiar",
                price: 2000,
                amountCriteria: 15,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier4 = {
                id: 13,
                categoryId: 2,
                tier: 4,
                name: "Master Familiar",
                price: 4000,
                amountCriteria: 25,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier5 = {
                id: 14,
                categoryId: 2,
                tier: 5,
                name: "Arcane Guardian",
                price: 10000,
                amountCriteria: 50,
                unlocked: false,
                buffMulti: 2,
            },
        ],
        alchemyTable = [
            strengthMultiplier1 = {
                id: 21,
                categoryId: 3,
                tier: 1,
                name: "Novice Alchemy Table",
                price: 800,
                amountCriteria: 5,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier2 = {
                id: 22,
                categoryId: 3,
                tier: 2,
                name: "Adept Alchemical Table",
                price: 4000,
                amountCriteria: 10,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier3 = {
                id: 23,
                categoryId: 3,
                tier: 3,
                name: "Masters Laboratory",
                price: 8000,
                amountCriteria: 15,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier4 = {
                id: 24,
                categoryId: 3,
                tier: 4,
                name: "Grand Alchemical Forge",
                price: 16000,
                amountCriteria: 25,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier5 = {
                id: 25,
                categoryId: 3,
                tier: 5,
                name: "Celestial Elixir Forge",
                price: 40000,
                amountCriteria: 50,
                unlocked: false,
                buffMulti: 2,
            },
        ],
        pylon = [
            strengthMultiplier1 = {
                id: 31,
                categoryId: 4,
                tier: 1,
                name: "Elemental Conduit",
                price: 3200,
                amountCriteria: 5,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier2 = {
                id: 32,
                categoryId: 4,
                tier: 2,
                name: "Arcane Pylon",
                price: 16000,
                amountCriteria: 10,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier3 = {
                id: 33,
                categoryId: 4,
                tier: 3,
                name: "Mystic Spire",
                price: 32000,
                amountCriteria: 15,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier4 = {
                id: 34,
                categoryId: 4,
                tier: 4,
                name: "Titans Spire",
                price: 64000,
                amountCriteria: 25,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier5 = {
                id: 35,
                categoryId: 4,
                tier: 5,
                name: "Celestial Beacon",
                price: 160000,
                amountCriteria: 50,
                unlocked: false,
                buffMulti: 2,
            },
        ],
        manaFountain = [
            strengthMultiplier1 = {
                id: 41,
                categoryId: 5,
                tier: 1,
                name: "Arcane Spring",
                price: 12800,
                amountCriteria: 5,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier2 = {
                id: 42,
                categoryId: 5,
                tier: 2,
                name: "Mystical Well",
                price: 64000,
                amountCriteria: 10,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier3 = {
                id: 43,
                categoryId: 5,
                tier: 3,
                name: "Enchanted Reservoir",
                price: 128000,
                amountCriteria: 15,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier4 = {
                id: 44,
                categoryId: 5,
                tier: 4,
                name: "Astral Spring",
                price: 256000,
                amountCriteria: 25,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier5 = {
                id: 45,
                categoryId: 5,
                tier: 5,
                name: "Celestial Font",
                price: 640000,
                amountCriteria: 50,
                unlocked: false,
                buffMulti: 2,
            },
        ],
        manaNexus = [
            strengthMultiplier1 = {
                id: 51,
                categoryId: 6,
                tier: 1,
                name: "Arcane Node",
                price: 51200,
                amountCriteria: 5,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier2 = {
                id: 52,
                categoryId: 6,
                tier: 2,
                name: "Mystical Conduit",
                price: 256000,
                amountCriteria: 10,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier3 = {
                id: 53,
                categoryId: 6,
                tier: 3,
                name: "Enchanted Junction",
                price: 512000,
                amountCriteria: 15,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier4 = {
                id: 54,
                categoryId: 6,
                tier: 4,
                name: "Ethereal Hub",
                price: 1024000,
                amountCriteria: 25,
                unlocked: false,
                buffMulti: 2,
            },
            strengthMultiplier5 = {
                id: 55,
                categoryId: 6,
                tier: 5,
                name: "Celestial Core",
                price: 2560000,
                amountCriteria: 50,
                unlocked: false,
                buffMulti: 2,
            },
        ],
    ],
};

let newUpdate = true;
const savedmodel = newUpdate ? "" : JSON.parse(localStorage.getItem('model'));
const model = savedmodel ? savedmodel : startmodel;